name: Deploy

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.0.0
      - uses: actions/cache@v2
        id: node_modules
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.node_modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Dev
        working-directory: standard-accounts
        run: npx tkm targets deploy Workload/Dev --yes
      - name: Test
        working-directory: standard-accounts
        run: npx tkm targets deploy Workload/Test --yes
      - name: Prod
        working-directory: standard-accounts
        run: npx tkm targets deploy Workload/Prod --yes